version: "3"
services:
  servername:
    container_name: ${SELFHOST}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
    build:
      context: .
      dockerfile: Dockerfile
    image: ${SELFHOST}-${CI_COMMIT_REF_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SELFHOST}Http${SELF_DOMAIN_NAME}.rule=Host(`${SELFHOST}${SELF_DOMAIN_NAME}.abclive.cloud`)"
      - "traefik.http.routers.${SELFHOST}Http${SELF_DOMAIN_NAME}.entrypoints=web"

      - "traefik.http.routers.${SELFHOST}Https${SELF_DOMAIN_NAME}.rule=Host(`${SELFHOST}${SELF_DOMAIN_NAME}.abclive.cloud`)"
      - "traefik.http.routers.${SELFHOST}Https${SELF_DOMAIN_NAME}.tls.certresolver=le"
      - "traefik.http.routers.${SELFHOST}Https${SELF_DOMAIN_NAME}.tls=true"
      - "traefik.http.routers.${SELFHOST}Https${SELF_DOMAIN_NAME}.entrypoints=websecure"

networks:
  default:
    external:
      name: traefik_default
