version: "3"
services:
  rtcWeb:
    container_name: ${APP}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    image: ${APP}-${CI_COMMIT_REF_NAME}
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.${APP}Https${GIT_BRANCH}.rule=Host(`${APP}${GIT_BRANCH}.abclive.cloud`)"
      - "traefik.http.routers.${APP}Https${GIT_BRANCH}.tls.certresolver=le"
      - "traefik.http.routers.${APP}Https${GIT_BRANCH}.tls=true"
      - "traefik.http.routers.${APP}Https${GIT_BRANCH}.entrypoints=websecure"

networks:
  default:
    external:
      name: traefik_default
